config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :restaurants do
    resources :reviews
  end

   root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	extend WithUserAssociationExtension

	has_many :reviews,
		-> { extending WithUserAssociationExtension },
	dependent: :destroy

	validates :name, length: {minimum: 3}, uniqueness: true

	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :rating, inclusion: (1..5)
  belongs_to :user
  belongs_to :restaurant

  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :reviews
  has_many :restaurants
		-> { extending WithUserAssociationExtension }
   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
   end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include?(restaurant)
  end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension

  def create_with_user(attributes = {}, user)
    attributes[:user] ||= user
    create(attributes)
  end


  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :authenticate_user!, :except => [:index, :show]

	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.create_with_user(restaurant_params, current_user)
		if @restaurant.save
			redirect_to restaurants_path
		else
			render 'new'
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(restaurant_params)

		redirect_to '/restaurants'
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:notice] = 'Restaurant deleted successfully'
		redirect_to '/restaurants'
	end

	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :description)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :authenticate_user!

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = Review.new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = @restaurant.reviews.build_with_user(review_params, current_user)

		if @review.save
			redirect_to restaurants_path
		else
			if @review.errors[:user]
				redirect_to restaurants_path alert: 'You have already reviewed this restaurant'
			else
				render :new
			end
		end
	end

	private

	def review_params
		params.require(:review).permit(:thoughts, :rating)
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

<% if user_signed_in? %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YelpClone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = notice
    = yield

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %> 
	<%= f.text_field :description %>
	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
	<% @restaurants.each do |restaurant| %>
		<h2> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
		<h2> <%= restaurant.description %> </h2>

		<% if current_user %>
			<% if current_user.id == @restaurants.find(restaurant.id).user_id %>
			<%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
			<% end %>
		<% end %>

		<% if current_user %>
			<% unless current_user.has_reviewed?(restaurant) %>
				<p> <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %> </p>
			<% end %>
		<% end %>

		<% restaurant.reviews.each do |review| %>
			<p> <%= review.rating %> </p>
			<p> <%= review.thoughts %> </p>
		<% end %>

		<% if current_user %>
			<% if current_user.id == @restaurants.find(restaurant.id).user_id %>
		<p> <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %></p>
			<% end %>
		<% end %>

	<% end %>

<% else %>
	<h1>No restaurants yet</h1>
<% end %>
<br>

<a href='/restaurants/new'>Add a restaurant</a>

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    = link_to restaurant.name, restaurant_path(restaurant)
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    = link_to "Review #{restaurant.name}", restaurant_path(restaurant)

    %h3
    Reviews for
    = restaurant.name

    - if restaurant.reviews.any?
      %ul
        - restaurant.reviews.each do |review|
        %li
          = review.thoughts
          %strong= review.rating
          \/5
    - else
      %p No reviews
      
- else
  %h1 no restaurants yet!

%a(href='/restaurants/new') add a restaurant

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
	<section id='errors'>
		<h2> <%= pluralize(@restaurant.errors.count, 'error') %> prohibited this restaurant from being saved: </h2>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</section>
<% end %>

<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/restaurants/new.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>
	<%= f.label :rating %>
	<%= f.select :rating, (1..5) %>
	<%= f.submit 'Leave Review' %>
<% end %>

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Restaurant', controller: 'restaurants' %>
<%=link_to 'New Restaurant', new_restaurant_path %>